### PR TITLE
[BACKLOG-13441] -- encoded rowLimit in the name of the transient data…

### PR DESCRIPTION
**Pull request by krivera-pentaho**
…service

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
@pentaho/ackbar @rfellows @bmorrise please review

**Comment by rfellows** [comment]
do we happen to have any tests for a negative row limit? i didn't see any when i checked.

**Comment by krivera-pentaho** [comment]
Updating PR

**Comment by krivera-pentaho** [comment]
@pentaho/ackbar @rfellows @bmorrise PR updated

**Pull request merged**
