### PR TITLE
[PDI-14537] Fix Local Data Service client

### PR DESCRIPTION
**Pull request by hudak**
http://jira.pentaho.com/browse/PDI-14537

### CODE REVIEW

**Comment by hudak** [comment]
[Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DskipTests -f pom.xml clean install && mvn -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceValidationException.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationService.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
  src/main/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServlet.java
  src/main/java/org/pentaho/di/trans/dataservice/www/ServletRepositoryAdapter.java
  src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
  src/main/resources/OSGI-INF/blueprint/services.xml
  src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationServiceTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPluginTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
  src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
  src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.dataservice.serialization.DataServiceMetaStoreUtil.4.new Supplier() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.clients.DataServiceClient:
 * instructionPercentCoverageChange : +0.42%
 * linePercentCoverageChange :**-0.79%**
 * complexityPercentCoverageChange :**-4.10%**
 * methodPercentCoverageChange :**-5.00%**
    
org.pentaho.di.trans.dataservice.serialization.DataServiceMetaStoreUtil.new DataServiceFactory() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceFactory:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :76.92%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :87.50%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceMetaStoreUtil.new Function() {...}:
 * instructionPercentCoverageChange :**-50.00%**
 * linePercentCoverageChange :**-66.67%**
 * complexityPercentCoverageChange :**-50.00%**
 * methodPercentCoverageChange :**-50.00%**
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate:
 * instructionPercentCoverageChange : +4.65%
 * linePercentCoverageChange : +4.57%
 * complexityPercentCoverageChange : +6.90%
 * methodPercentCoverageChange : +10.53%
    
org.pentaho.di.trans.dataservice.www.ServletRepositoryAdapter:
 * linePercentCoverage :57.14%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :60.00%
    
org.pentaho.di.trans.dataservice.www.TransDataServlet:
 * instructionPercentCoverageChange :**-0.13%**
 * linePercentCoverageChange :**-0.15%**
    
org.pentaho.di.trans.dataservice.serialization.DataServiceMetaStoreUtil:
 * instructionPercentCoverageChange : +0.78%
 * linePercentCoverageChange : +0.57%
 * complexityPercentCoverageChange : +1.89%
 * methodPercentCoverageChange : +3.45%
    
org.pentaho.di.trans.dataservice.serialization.SynchronizationService:
 * instructionPercentCoverageChange :**-60.92%**
 * branchPercentCoverageChange :**-66.67%**
 * linePercentCoverageChange :**-52.00%**
 * complexityPercentCoverageChange :**-58.33%**
 * methodPercentCoverageChange :**-55.56%**
    
org.pentaho.di.trans.dataservice.www.ListDataServicesServlet:
 * instructionPercentCoverageChange :**-0.81%**
 * linePercentCoverageChange :**-0.98%**

**Comment by lucboudreau** [comment]
Drop in coverage in a few classes.

**Comment by hudak** [comment]
I disabled SynchronizationServiceTest, which is the one failing on devci. Should I leave it enabled?

**Pull request closed without merging**
