### PR TITLE
[PDI-15584] It's possible to create data services with duplicate name s via Save AS button for transformations

### PR DESCRIPTION
**Pull request by AliaksandrShuhayeu**
[PDI-15584] It's possible to create data services with duplicate name s via Save AS button for transformations

-remove dataService if user pressed NO in dialog

### CODE REVIEW

**Comment by AliaksandrShuhayeu** [comment]
@mbatchelor Could you please review and merge it?

**Comment by kolinus** [comment]
@mdamour1976 @pamval could you please take a look

**Comment by mchen-len-son** [comment]
@DFieldFL @hudak @mbatchelor could you please take a look?
thanks.

**Comment by DFieldFL** [comment]
@kurtwalker mind taking a look?

**Pull request merged**
