### PR TITLE
Additional Testing

### PR DESCRIPTION
**Pull request by hudak**
[Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)

### CODE REVIEW

**Comment by hudak** [comment]
http://10.100.11.222:8080/job/wingman-mvn/38/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DskipTests -f pom.xml clean install && mvn -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceValidationException.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationService.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPlugin.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
  src/test/java/org/pentaho/di/trans/dataservice/BaseTest.java
  src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationServiceTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPluginTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
1. src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java







Unit test coverage change:
============
org.pentaho.di.trans.dataservice.serialization.TransOpenedExtensionPointPlugin:
 * instructionPercentCoverageChange : +36.36%
 * linePercentCoverageChange : +25.00%
 * complexityPercentCoverageChange : +33.33%
 * methodPercentCoverageChange : +33.33%
    
org.pentaho.di.trans.dataservice.ui.controller.DataServiceDialogController:
 * instructionPercentCoverageChange :**-0.15%**
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate:
 * instructionPercentCoverageChange : +8.69%
 * linePercentCoverageChange : +12.21%
 * complexityPercentCoverageChange : +14.22%
 * methodPercentCoverageChange : +17.94%
    
org.pentaho.di.trans.dataservice.DataServiceContext:
 * linePercentCoverage :89.47%
 * methodPercentCoverage :90.91%
 * complexityPercentCoverage :90.91%
 * instructionPercentCoverage :83.08%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceMetaStoreUtil:
 * instructionPercentCoverageChange : +0.79%
 * linePercentCoverageChange : +1.44%
 * complexityPercentCoverageChange : +0.14%
 * methodPercentCoverageChange : +0.11%
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate.new Supplier() {...}:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :60.00%

**Comment by hudak** [comment]
@bmorrise

**Comment by lucboudreau** [comment]
One license missing: src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java

**Pull request merged**
