### PR TITLE
[PDI-15153] Creating Data Services via View Panel - New Data ServiceParameter Pushdown - Error with Parameters not showing up

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- When creating data service with no service - step specified, take the last step from active transformation and mark it sa service - step
- Tests written
- Checkstyle applied

### CODE REVIEW

**Comment by IvanNikolaychuk** [comment]
@mchen-len-son , could you review this PR, please?

**Comment by mchen-len-son** [comment]
@hudak please take a look

It looks OK from my point of view.

**Comment by IvanNikolaychuk** [comment]
@hudak could you please take a look at this PR?

**Comment by hudak** [comment]
@IvanNikolaychuk @mchen-len-son 
Will review, thank you!

**Pull request merged**
