### PR TITLE
[BACKLOG-3195] Added invalid cache for stop and fail

### PR DESCRIPTION
**Pull request by bmorrise**
http://jira.pentaho.com/browse/BACKLOG-3195

[Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin)

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.1 -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/CommandQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DualQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/Query.java
  src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
  src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
  src/test/java/org/pentaho/di/trans/dataservice/CommandExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
  src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
1. Message: 'private' modifier out of order with the JLS suggestions. at Line: 101 Column: 12

File src/main/java/org/pentaho/di/trans/dataservice/clients/CommandQueryService.java
1. Message: ':' should be on a new line. at Line: 59 Column: 91

File src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
1. Message: '?' should be on a new line. at Line: 67 Column: 53
2. Message: ':' should be on a new line. at Line: 68 Column: 43

File src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
1. Message: ')' have incorrect indentation level 0, expected level should be 2. at Line: 62 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.dataservice.CommandExecutor.ExecutorCommand:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.CommandExecutor.Builder:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate:
 * instructionPercentCoverageChange : +0.06%
    
org.pentaho.di.trans.dataservice.CommandExecutor.StopCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :88.89%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :93.33%
    
org.pentaho.di.trans.dataservice.CommandExecutor:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor.Builder:
 * instructionPercentCoverageChange : +0.70%
 * linePercentCoverageChange : +0.65%
    
org.pentaho.di.trans.dataservice.clients.CommandQueryService:
 * branchPercentCoverage :25.00%
 * linePercentCoverage :71.43%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :34.29%
    
org.pentaho.di.trans.dataservice.CommandExecutor.ErrorsCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :85.71%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :92.31%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor:
 * instructionPercentCoverageChange :**-0.23%**
 * branchPercentCoverageChange :**-1.67%**
 * linePercentCoverageChange : +0.03%
 * complexityPercentCoverageChange :**-1.77%**
    
org.pentaho.di.trans.dataservice.clients.DataServiceClient:
 * instructionPercentCoverageChange :**-7.31%**
 * linePercentCoverageChange :**-3.46%**
 * complexityPercentCoverageChange : +2.27%
 * methodPercentCoverageChange : +2.78%
    
org.pentaho.di.trans.dataservice.ui.controller.DataServiceTestController:
 * instructionPercentCoverageChange :**-0.24%**
 * linePercentCoverageChange : +0.07%
    
org.pentaho.di.trans.dataservice.optimization.cache.ServiceCache.new FutureCallback() {...}:
 * instructionPercentCoverageChange : +0.91%
 * branchPercentCoverageChange :**-1.67%**
 * complexityPercentCoverageChange :**-4.17%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :81.82%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :92.47%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceFactory:
 * instructionPercentCoverageChange :**-1.45%**
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :95.24%
    
org.pentaho.di.trans.dataservice.DataServiceContext:
 * instructionPercentCoverageChange :**-10.91%**
 * linePercentCoverageChange :**-9.68%**
 * complexityPercentCoverageChange :**-14.29%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.trans.dataservice.ui.DataServiceTestDialog:
 * instructionPercentCoverageChange :**-0.01%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService.DualQuery:
 * linePercentCoverage :80.00%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :83.33%
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService.ExecutorQuery:
 * linePercentCoverage :83.33%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :61.90%
    
org.pentaho.di.trans.dataservice.www.TransDataServlet:
 * instructionPercentCoverageChange :**-0.60%**
 * branchPercentCoverageChange : +2.27%
 * linePercentCoverageChange :**-0.28%**
 * complexityPercentCoverageChange : +6.19%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.1 -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/CommandQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DualQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/Query.java
  src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
  src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
  src/test/java/org/pentaho/di/trans/dataservice/CommandExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
  src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
1. Message: 'private' modifier out of order with the JLS suggestions. at Line: 55 Column: 12









Unit test coverage change:
============
org.pentaho.di.trans.dataservice.CommandExecutor.ExecutorCommand:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.CommandExecutor.Builder:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate:
 * instructionPercentCoverageChange : +0.06%
    
org.pentaho.di.trans.dataservice.CommandExecutor.StopCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :88.89%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :93.33%
    
org.pentaho.di.trans.dataservice.CommandExecutor:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor.Builder:
 * instructionPercentCoverageChange : +0.70%
 * linePercentCoverageChange : +0.65%
    
org.pentaho.di.trans.dataservice.clients.CommandQueryService:
 * branchPercentCoverage :25.00%
 * linePercentCoverage :71.43%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :34.29%
    
org.pentaho.di.trans.dataservice.CommandExecutor.ErrorsCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :85.71%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :92.31%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor:
 * instructionPercentCoverageChange :**-0.23%**
 * branchPercentCoverageChange :**-1.67%**
 * linePercentCoverageChange : +0.03%
 * complexityPercentCoverageChange :**-1.77%**
    
org.pentaho.di.trans.dataservice.clients.DataServiceClient:
 * instructionPercentCoverageChange :**-7.31%**
 * linePercentCoverageChange :**-3.46%**
 * complexityPercentCoverageChange : +2.27%
 * methodPercentCoverageChange : +2.78%
    
org.pentaho.di.trans.dataservice.ui.controller.DataServiceTestController:
 * instructionPercentCoverageChange :**-0.24%**
 * linePercentCoverageChange : +0.07%
    
org.pentaho.di.trans.dataservice.optimization.cache.ServiceCache.new FutureCallback() {...}:
 * instructionPercentCoverageChange : +0.91%
 * branchPercentCoverageChange :**-1.67%**
 * complexityPercentCoverageChange :**-4.17%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :81.82%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :92.47%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceFactory:
 * instructionPercentCoverageChange :**-1.45%**
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :95.24%
    
org.pentaho.di.trans.dataservice.DataServiceContext:
 * instructionPercentCoverageChange :**-10.91%**
 * linePercentCoverageChange :**-9.68%**
 * complexityPercentCoverageChange :**-14.29%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.trans.dataservice.ui.DataServiceTestDialog:
 * instructionPercentCoverageChange :**-0.01%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService.DualQuery:
 * linePercentCoverage :80.00%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :83.33%
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService.ExecutorQuery:
 * linePercentCoverage :83.33%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :61.90%
    
org.pentaho.di.trans.dataservice.www.TransDataServlet:
 * instructionPercentCoverageChange :**-0.60%**
 * branchPercentCoverageChange : +2.27%
 * linePercentCoverageChange :**-0.28%**
 * complexityPercentCoverageChange : +6.19%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.1 -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
  src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/CommandQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/DualQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
  src/main/java/org/pentaho/di/trans/dataservice/clients/Query.java
  src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
  src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
  src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
  src/test/java/org/pentaho/di/trans/dataservice/CommandExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
  src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
  src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
  src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
  src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
  src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java










Unit test coverage change:
============
org.pentaho.di.trans.dataservice.CommandExecutor.ExecutorCommand:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.CommandExecutor.Builder:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.ui.DataServiceDelegate:
 * instructionPercentCoverageChange : +0.06%
    
org.pentaho.di.trans.dataservice.CommandExecutor.StopCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :88.89%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :93.33%
    
org.pentaho.di.trans.dataservice.CommandExecutor:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor.Builder:
 * instructionPercentCoverageChange : +0.70%
 * linePercentCoverageChange : +0.65%
    
org.pentaho.di.trans.dataservice.clients.CommandQueryService:
 * branchPercentCoverage :25.00%
 * linePercentCoverage :71.43%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :34.29%
    
org.pentaho.di.trans.dataservice.CommandExecutor.ErrorsCommand:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :85.71%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :92.31%
    
org.pentaho.di.trans.dataservice.DataServiceExecutor:
 * instructionPercentCoverageChange :**-0.23%**
 * branchPercentCoverageChange :**-1.67%**
 * linePercentCoverageChange : +0.03%
 * complexityPercentCoverageChange :**-1.77%**
    
org.pentaho.di.trans.dataservice.clients.DataServiceClient:
 * instructionPercentCoverageChange :**-7.31%**
 * linePercentCoverageChange :**-3.46%**
 * complexityPercentCoverageChange : +2.27%
 * methodPercentCoverageChange : +2.78%
    
org.pentaho.di.trans.dataservice.ui.controller.DataServiceTestController:
 * instructionPercentCoverageChange :**-0.24%**
 * linePercentCoverageChange : +0.07%
    
org.pentaho.di.trans.dataservice.optimization.cache.ServiceCache.new FutureCallback() {...}:
 * instructionPercentCoverageChange : +0.91%
 * branchPercentCoverageChange :**-1.67%**
 * complexityPercentCoverageChange :**-4.17%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :81.82%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :92.47%
    
org.pentaho.di.trans.dataservice.serialization.DataServiceFactory:
 * instructionPercentCoverageChange :**-1.45%**
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :95.24%
    
org.pentaho.di.trans.dataservice.DataServiceContext:
 * instructionPercentCoverageChange :**-10.91%**
 * linePercentCoverageChange :**-9.68%**
 * complexityPercentCoverageChange :**-14.29%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.trans.dataservice.ui.DataServiceTestDialog:
 * instructionPercentCoverageChange :**-0.01%**
    
org.pentaho.di.trans.dataservice.clients.DualQueryService.DualQuery:
 * linePercentCoverage :80.00%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :83.33%
    
org.pentaho.di.trans.dataservice.clients.ExecutorQueryService.ExecutorQuery:
 * linePercentCoverage :83.33%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :61.90%
    
org.pentaho.di.trans.dataservice.www.TransDataServlet:
 * instructionPercentCoverageChange :**-0.60%**
 * branchPercentCoverageChange : +2.27%
 * linePercentCoverageChange :**-0.28%**
 * complexityPercentCoverageChange : +6.19%

**Comment by bmorrise** [comment]
@hudak Please review

**Pull request merged**
